# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_media', '0004_auto_20170109_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='model',
        ),
        migrations.RemoveField(
            model_name='media',
            name='model_object',
        ),
    ]
